CREATE DATABASE IF NOT EXISTS auth_db;
CREATE DATABASE IF NOT EXISTS vehicle_db;
CREATE DATABASE IF NOT EXISTS driver_db;
CREATE DATABASE IF NOT EXISTS route_db;
CREATE DATABASE IF NOT EXISTS trip_db;
CREATE DATABASE IF NOT EXISTS location_db;
